### ISSUE TITLE
Cannot figure out why this regex is not working

### ISSUE THREAD

**Issue by dacree0626** [dacree0626/automation#5]
https://github.com/dacree0626/automation/blob/21384d1fdadb1cd213825ea3a16e40c2f6e2c052/javascript/edabit.js#L179

So I've tried all sorts of variations provided by stackoverflow: https://stackoverflow.com/questions/12936903/match-returning-null-in-javascript but I cannot figure out why I always get 'null' when this code runs. Love your take on it

**Comment by dacree0626** [comment]
Other things i've tried
`var re = /^(0?[1-9]|1[0-2]):[0-5][0-9]$/`
`var re = new RegExp("^(0?[1-9]|1[0-2]):[0-5][0-9]$")`

**Comment by silenceisgolden** [comment]
https://blog.codinghorror.com/regular-expressions-now-you-have-two-problems/
https://blog.cloudflare.com/details-of-the-cloudflare-outage-on-july-2-2019/
